        <div class="container">
            <div id="principal">
                <section class="seran">
                    <h4>Séries et Animés en streaming</h4>
                    <div>
                        <article>
                            <h5>LES SÉRIES TV DISPONIBLES</h5>
                            <ul>
                                <li><a href="#">Prison Break</a></li>
                                <li><a href="#">Hawaii 5:0</a></li>
                                <li><a href="#">Lucifer</a></li>
                                <li><a href="#">Bad Blood</a></li>
                                <li><a href="#">Blacklist</a></li>
                                <li><a href="#">La Casa De Papel</a></li>
                                <li><a href="#">Game Of Thrones</a></li>
                                <li><a href="#">Breaking Bad</a></li>
                                <li><a href="#">The Walking Dead</a></li>
                                <li><a href="#">Vikings</a></li>
                            </ul>
                        </article>
                        <article>
                            <h5>LES ANIMES DISPONIBLES</h5>
                            <ul>
                                <li><a href="#">One Piece</a></li>
                                <li><a href="#">Jojo's Bizarre Adventure</a></li>
                                <li><a href="#">Death Note</a></li>
                                <li><a href="#">Hunter X Hunter</a></li>
                                <li><a href="#">One Punch Man</a></li>
                                <li><a href="#">Kimetsu No Yaiba</a></li>
                                <li><a href="#">Shingeki No Kyojin</a></li>
                                <li><a href="#">Naruto</a></li>
                                <li><a href="#">Dr Stone</a></li>
                                <li><a href="#">My Hero Academia</a></li>
                            </ul>
                        </article>
                    </div>
                </section>

                <section class="film">
                    <h4>Films en streaming</h4>
                    <div>
                        <a href="movies/page_film/movie.php?movie=bad_boys_for_life"><img alt="Image de Bad boys for life" src="img/bad-boys.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=birds"><img alt="Image de Birds of prey" src="img/birds.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=john_wick"><img alt="Image de John whick" src="img/john.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=end_game"><img alt="Image de Avengers" src="img/end-game.jpg" alt="*"></a>
                    </div>
                    <div>
                        <a href="movies/page_film/movie.php?movie=mahnattan"><img alt="Image de Mahnattan" src="img/manhattan.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=ça"><img alt="Image de Ca" src="img/ca.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=la_nonne"><img alt="Image de La nonne" src="img/nonne.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=annabelle"><img alt="Image de Annabelle" src="img/anna.jpg" alt="*"></a>
                    </div>
                    <div>
                        <a href="movies/page_film/movie.php?movie=OP_stampede"><img alt="Image de One piece" src="img/stampede.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=dbs_broly"><img alt="Image de Dbs_broly" src="img/dbs.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=terminator"><img alt="Image de Terminator" src="img/terminator.jpg" alt="*"></a>
                        <a href="movies/page_film/movie.php?movie=joker"><img alt="Image de Joker" src="img/joker.webp" alt="*"></a>
                    </div>
                </section>
            </div>