<?php
if(isset($_SESSION['modify'])){
    $article = $_SESSION['modify'];
}else{
    $article = "";
}
?>
<div id="Articles">
    <div>
        <form action="ajouter.php" method="post">
            <h1>Ajouter un article</h1>
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom" id="nom" required="required">
            </div>
            <div>
                <label for="stock">Stock:</label>
                <input type="number" name="stock" id="stock" required="required">
            </div>
            <div>
                <label for="prix">Prix:</label>
                <input type="number" name="prix" id="prix" required="required">
            </div>
            <div>
                <label for="code">Code:</label>
                <input type="text" name="code" id="code" required="required">
            </div>
            <div>
                <label for="liens">Liens images:</label>
                <input type="text" name="liens" id="liens" placeholder="Liens des images séparé pas des virgules" required="required">
            </div>
            <div>
                <label for="description">Description:</label>
                <textarea name="description" id="description" rows="50"></textarea>
            </div>
            <div>
                <input type="submit" value="Ajouter" class="btn">
            </div>
        </form>
        <form action="modifier.php" method="post">
            <h1>Modifier un article</h1>
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom" id="nom" required="required" value="<?=$article['nom']?>">
            </div>
            <div>
                <label for="stock">Stock:</label>
                <input type="number" name="stock" id="stock" required="required" value="<?=$article['stock']?>">
            </div>
            <div>
                <label for="prix">Prix:</label>
                <input type="number" name="prix" id="prix" required="required" value="<?=$article['prix']?>">
            </div>
            <div>
                <label for="code">Code:</label>
                <input type="text" name="code" id="code" required="required" value="<?=$article['code']?>" readonly>
            </div>
            <div>
                <label for="liens">Liens images:</label>
                <input type="text" name="liens" id="liens" placeholder="Liens des images séparé pas des virgules" required="required" value="<?=$article['img']?>">
            </div>
            <div>
                <label for="description">Description:</label>
                <textarea name="description" id="description" rows="50"><?=$article['description']?>"</textarea>
            </div>
            <div>
                <input type="submit" value="Modifier" class="btn">
            </div>
        </form>
        <?php
            if(isset($modify) && $modify){
                echo "<p style=\"color:green;\">Article modifier avec succés</p>";
            }else if(isset($ajout) && $ajout){
                echo "<p style=\"color:green;\">Article ajouter avec succés</p>";
            }
        ?>
</div>