<div id="accueil">
    <div class="app">
        <h2>A propos de nous</h2>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
        </p>
        <p>
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
            Lorem, ipsum dolor sit amet consectetur adipisicing elit.
            In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
            inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
            voluptas harum.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
            quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
            voluptas at dolorum ab doloribus.
        </p>
    </div>
    <div class="md">
        <div>
            <h2>Participer à nos maraudes</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit sapiente tenetur,
                recusandae eius numquam harum eligendi nesciunt ex praesentium inventore dicta laborum
                doloremque ea unde delectus vero a eum sunt.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
                inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
                voluptas harum.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
                quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
                voluptas at dolorum ab doloribus.                
            </p>
            <p>Vous voulez participer à un de nos maraudes, remplissez le formulaire de participation 
                en cliquant <a href="maraude.php" target="_blank" rel="noopener noreferrer">ici</a>
            </p>
        </div>
        <div>
            <h2>Dons</h2>
            <p>
                Lorem ipsum dolor sit amet consectetur, adipisicing elit. Velit sapiente tenetur,
                recusandae eius numquam harum eligendi nesciunt ex praesentium inventore dicta laborum
                doloremque ea unde delectus vero a eum sunt.
                Lorem, ipsum dolor sit amet consectetur adipisicing elit.
                In obcaecati eum facere numquam soluta magnam deserunt explicabo, 
                inventore vero molestiae vitae autem. Nulla quia autem sed numquam assumenda 
                voluptas harum.
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ullam impedit illum 
                quaerat nam amet quibusdam a harum numquam. Beatae delectus quia tempore dicta debitis
                voluptas at dolorum ab doloribus.                
            </p>
            <p>Vous voulez nous soutenir, envoyer nous vos dons par paypal en cliquant <a href="https://www.paypal.com/paypalme/aichahumaniteam?country.x=FR&locale.x=fr_FR" target="_blank" rel="noopener noreferrer">ici</a>
            </p>
        </div>
    </div>
</div>