<div id="contact">
    <section>
        <h3>Ecrivez-nous</h3>
        <form action="contactez-nous.php" method="post">
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom">
            </div>
            <div>
                <label for="prenom">Prénom:</label>
                <input type="text" name="prenom">
            </div>
            <div>
                <label for="email">E-mail:</label>
                <input type="email" name="email">
            </div>
            <div>
                <label for="msg">Votre message</label>
                <textarea name="msg" id="msg" cols="30" rows="10"></textarea>
            </div>
            <div>
                <input type="submit" value="Envoyer">
            </div>
        </form>
    </section>
    <section>
        <h3>Contacts</h3>
        <div>
            <p>Nom: CISSE Mounirou</p>
            <p>Email: <a href="mailto:mounirou.cisse@outlook.fr">mounirou.cisse@outlook.fr</a></p>
            <p>Numéro: <a href="tel:+33627530696">06 27 53 06 96</a></p>
        </div>
        <div>
            <p>Nom: KANOUTE Mohamed</p>
            <p>Email: <a href="mailto:">Mets ton mail</a></p>
            <p>Numéro: <a href="tel:+">Mets ton num</a></p>
        </div>
    </section>
</div>