<div id="engager">
    <section>
        <h3>S'inscrire dans l'association</h3>
        <form action="engager.php" method="post">
            <div>
                <label for="nom">Nom:</label>
                <input type="text" name="nom">
            </div>
            <div>
                <label for="prenom">Prénom:</label>
                <input type="text" name="prenom">
            </div>
            <div>
                <label for="email">E-mail:</label>
                <input type="email" name="email">
            </div>
            <div>
                <label for="num">Numéro de téléphone:</label>
                <input type="text" name="num">
            </div>
            <div>
                <input type="submit" value="S'inscrire">
            </div>
        </form>

    </section>
    <section>
        <h3>Administrateur !!!!</h3>
        <form action="engager.php" method="post">
            <div>
                <label for="pseudo">Pseudo:</label>
                <input type="text" name="pseudo">
            </div>
            <div>
                <label for="mdp">Mot de passe:</label>
                <input type="password" name="mdp">
            </div>
            <div>
                <input type="submit" value="Se connecter">
            </div>
        </form>

    </section>
</div>