<section class="film">
    <section>
        <article><a href="https://wwv.voirfilms.media/007-spectre-sKcx1pmAkrx.htm"><img alt="Image de " src="../img/007.jpg"></a></article>
        <article><a href="https://wwv.voirfilms.media/boruto-naruto-le-film-zJHLX4IF.htm"><img alt="Image de " src="../img/boruto.jpg"></a></article>
        <article><a href="https://wwv.voirfilms.media/mission-impossible-fallout-HbwYUERev.htm"><img alt="Image de " src="../img/fallout.jpg"></a></article>
        <article><a href="https://wwv.voirfilms.media/captain-marvel.htm"><img alt="Image de " src="../img/marvel.jpg"></a></article>
    </section>
    <section>
        <article><a href="../movies/page_film/movie.php?movie=annabelle"><img alt="Image de Annabelle" src="../img/anna.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=bad_boys_for_life"><img alt="Image de Bad boys for life" src="../img/bad-boys.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=birds"><img alt="Image de Birds of prey" src="../img/birds.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=ça"><img alt="Image de Ca" src="../img/ca.jpg"></a></article>
    </section>
    <section>
        <article><a href="../movies/page_film/movie.php?movie=dbs_broly"><img alt="Image de Dbs broly" src="../img/dbs.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=end_game"><img alt="Image de Avengers" src="../img/end-game.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=john_wick"><img alt="Image de John wick" src="../img/john.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=joker"><img alt="Image de " src="../img/joker.webp"></a></article>
    </section>
    <section>
        <article><a href="../movies/page_film/movie.php?movie=mahnattan"><img alt="Image de Mahnattan" src="../img/manhattan.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=la_nonne"><img alt="Image de La nonne" src="../img/nonne.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=OP_stampede"><img alt="Image de One piece" src="../img/stampede.jpg"></a></article>
        <article><a href="../movies/page_film/movie.php?movie=terminator"><img alt="Image de Terminator" src="../img/terminator.jpg"></a></article>
    </section>
</section>
    