<?php 
session_start();
if (isset($_GET['deco']) && $_GET['deco'] === 'true') {
    session_destroy();
    header("Location: index.php");
    die();
}
?>
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/45e38e596f.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="css/style.css">
    <link rel="shortcut icon" href="img/logo.png" type="image/x-icon">
    <title><?=$title?></title>
</head>
<body>
    <header id="pc">
        <div>
            <a href="index.php">
                <img src="img/logo.png" alt="Logo de l'association" style="margin-right: 15px;">
                <h1>Humaniteam</h1>
            </a>
        </div>
        <nav>
            <a href="maraude.php"><i class="fas fa-shopping-cart"></i><span>Nos Maraudes</span></a>
            <a href="contactez-nous.php"><i class="fas fa-id-card"></i><span>Contactez-nous</span></a>
            <a href="engager.php"><i class="fas fa-users"></i><span>S'engager</span></a>
            <?php if(isset($_SESSION['admin'])){?>
                <a href="?deco=true"><i class="fa-solid fa-right-from-bracket"></i><span>Déconnexion</span></a>
            <?php } ?>
        </nav>
    </header>
    <header id="phone">
        <div>
            <a href="index.php">
                <img src="img/logo.png" alt="Logo de l'association" style="margin-right: 15px;">
            </a>
        </div>
        <input type="checkbox" class="burger">
        <nav>
            <a href="maraude.php"><i class="fas fa-shopping-cart"></i><span>Nos Maraudes</span></a>
            <a href="contactez-nous.php"><i class="fas fa-id-card"></i><span>Contactez-nous</span></a>
            <a href="engager.php"><i class="fas fa-users"></i><span>S'engager</span></a>
            <?php if(isset($_SESSION['admin'])){?>
                <a href="?deco=true"><i class="fa-solid fa-right-from-bracket"></i><span>Déconnexion</span></a>
            <?php } ?>
        </nav>
    </header>
    <main>
        <?php require "views/".$template.".phtml";?>
    </main>
    <footer>
        <div>
            <h3>Nos partenaires</h3>
            <div>
                <img src="" alt="">
            </div>
        </div>
        <div>
            <h3>Nos réseaux</h3>
            <div>
                <a href="http://" target="_blank" rel="noopener noreferrer"><i class="fab fa-facebook"></i><span>Facebook</span></a>
                <a href="http://" target="_blank" rel="noopener noreferrer"><i class="fab fa-instagram"></i><span>Instagram</span></a>
                <a href="http://" target="_blank" rel="noopener noreferrer"><i class="fab fa-snapchat"></i><span>Snapchat</span></a>
            </div>
        </div>
    </footer>
</body>
<script src="//code.jquery.com/jquery-1.12.0.min.js"></script>
<script src="js/main.js"></script>
</html>