<div class="bg">
    <section class="bg1" aria-label="Photos">
        <div class="carousel" data-carousel>
            <button class="carousel-button prev" data-carousel-button="prev"><i class="fas fa-arrow-right"></i></button>
            <button class="carousel-button next" data-carousel-button="next"><i class="fas fa-arrow-left"></i></button>
            <ul data-slides>
                <li class="slide" data-active>
                    <img src="https://cdn.pixabay.com/photo/2015/04/19/08/32/rose-729509_960_720.jpg" alt="image1">
                </li>
                <li class="slide">
                    <img src="https://cdn.pixabay.com/photo/2017/01/18/17/14/girl-1990347_960_720.jpg" alt="image2">
                </li>
                <li class="slide">
                    <img src="https://cdn.pixabay.com/photo/2018/08/16/19/56/wedding-rings-3611277_960_720.jpg" alt="image3">
                </li>
            </ul>
        </div>
    </section>
    <section class="bg2">
        <div class="box1">
            <img src="/img/carousel/image2.png" alt="">
        </div>
        <div class="text1">
            <p>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.      
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.      
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nostrum ipsam eum commodi modi reprehenderit dolore quasi aspernatur, consectetur error eos vero eligendi similique minima, consequuntur fuga dolorem. Minima, ipsam.      
            </p>
        </div>
    </section>
    <section class="bg3">
        <h1>text</h1>
    </section>
</div>
<div class="bg1-2">
    <div>
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Quibusdam cum autem perferendis hic ipsum recusandae, pariatur vero culpa aut voluptates minus numquam eaque sed quaerat facilis incidunt error tempore fugit?
        Lorem ipsum dolor, sit amet consectetur adipisicing elit. Quo nobis, atque harum nesciunt dolor suscipit nisi nam cupiditate perferendis illum. Quas non suscipit, debitis consequuntur magnam ratione praesentium ipsum repellat!
        Lorem ipsum dolor sit amet consectetur adipisicing elit. Distinctio praesentium illo ipsum, eligendi quas sequi tempora in, quisquam harum dolorem esse ex voluptatibus nesciunt veniam culpa. Minus a doloribus officia?
    </div>
</div>