<!doctype html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="css_page_phtml/pages.css" type="text/css" />
    <title>Modificatuon d'informations</title>
</head>
<body class="body">
    <section>
        <form action="changement2.php" method="POST">
            
            <div>
            	<label for='newPseudo'>Votre nouveau pseudo</label><br/>
            	<input type='text' name='newPseudo' id='pseudo'/>
            </div><br/>
            <div>
            	<label for='newEmail'>Votre nouveau email</label><br/>
            	<input type='text' name='newEmail' />
            </div><br/>
            <input type='submit' name='valider'/>
        </form>
    </section>
</body>
</html>